# Setup
title:               'Projet d'équipe pour le cours IFT-6758 (UdeM)'
tagline:             'Automne 2023'
description:         'Structure du blog'
url:                 https://julien-hebert-doutreloux.github.io/Project-Blog-IFT6758-A23/
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              MJHD
  url:               https://github.com/julien-hebert-doutreloux/
  email:             jhd@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
